// Generated by https://quicktype.io

export interface Schedule {
  data: Data;
}

export interface Data {
  schedule: ScheduleClass;
}

export interface ScheduleClass {
  pages: Pages;
  events: Event[];
}

export interface Event {
  startTime: string;
  state: string;
  type: EventType;
  blockName: BlockName;
  league: League;
  match: Match;
}

export enum BlockName {
  EliminatóriasDaFaseDeEntrada = 'Eliminatórias da Fase de Entrada',
  FaseDeEntradaGrupos = 'Fase de Entrada - Grupos',
  Finais = 'Finais',
  Grupos = 'Grupos',
  QuartasDeFinal = 'Quartas de Final',
  Semifinais = 'Semifinais',
}

export interface League {
  name: Name;
  slug: Slug;
}

export enum Name {
  Mundial = 'Mundial',
}

export enum Slug {
  Worlds = 'worlds',
}

export interface Match {
  id: string;
  flags: Flag[];
  teams: Team[];
  strategy: Strategy;
}

export enum Flag {
  HasVOD = 'hasVod',
  IsSpoiler = 'isSpoiler',
}

export interface Strategy {
  type: StrategyType;
  count: number;
}

export enum StrategyType {
  BestOf = 'bestOf',
}

export interface Team {
  name: string;
  code: string;
  image: string;
  result: Result;
  record: Record;
}

export interface Record {
  wins: number;
  losses: number;
}

export interface Result {
  outcome: Outcome;
  gameWins: number;
}

export enum Outcome {
  Loss = 'loss',
  Win = 'win',
}

export enum State {
  Completed = 'completed',
}

export enum EventType {
  Match = 'match',
}

export interface Pages {
  older: string;
  newer: null;
}
