// Generated by https://quicktype.io

export interface DataGameDetails {
  data: Data;
}

export interface Data {
  event: Event;
}

export interface Event {
  id: string;
  type: string;
  tournament: Tournament;
  league: League;
  match: Match;
  streams: any[];
}

export interface League {
  id: string;
  slug: string;
  image: string;
  name: string;
}

export interface Match {
  strategy: Strategy;
  teams: MatchTeam[];
  games: Game[];
}

export interface Game {
  number: number;
  id: string;
  state: string;
  teams: GameTeam[];
  vods: VOD[];
}

export interface GameTeam {
  id: string;
  side: Side;
}

export enum Side {
  Blue = 'blue',
  Red = 'red',
}

export interface VOD {
  id: string;
  parameter: string;
  locale: string;
  mediaLocale: MediaLocale;
  provider: Provider;
  offset: number;
  firstFrameTime: null | string;
  startMillis: null;
  endMillis: null;
}

export interface MediaLocale {
  locale: string;
  englishName: string;
  translatedName: string;
}

export enum Provider {
  Youtube = 'youtube',
}

export interface Strategy {
  count: number;
}

export interface MatchTeam {
  id: string;
  name: string;
  code: string;
  image: string;
  result: Result;
}

export interface Result {
  gameWins: number;
}

export interface Tournament {
  id: string;
}
