// Generated by https://quicktype.io

export interface GameDetails {
  esportsGameId: string;
  esportsMatchId: string;
  gameMetadata: GameMetadata;
  frames: Frame[];
}

export interface Frame {
  rfc460Timestamp: string;
  gameState: GameState;
  blueTeam: Team;
  redTeam: Team;
}

export interface Team {
  totalGold: number;
  inhibitors: number;
  towers: number;
  barons: number;
  totalKills: number;
  dragons: Dragon[];
  participants: Participant[];
}

export enum Dragon {
  Elder = 'elder',
  Infernal = 'infernal',
  Mountain = 'mountain',
  Ocean = 'ocean',
}

export interface Participant {
  participantId: number;
  totalGold: number;
  level: number;
  kills: number;
  deaths: number;
  assists: number;
  creepScore: number;
  currentHealth: number;
  maxHealth: number;
}

export enum GameState {
  Finished = 'finished',
  InGame = 'in_game',
}

export interface GameMetadata {
  patchVersion: string;
  blueTeamMetadata: TeamMetadata;
  redTeamMetadata: TeamMetadata;
}

export interface TeamMetadata {
  esportsTeamId: string;
  participantMetadata: ParticipantMetadatum[];
}

export interface ParticipantMetadatum {
  participantId: number;
  esportsPlayerId: string;
  summonerName: string;
  championId: string;
  role: string;
}
